import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsBoolean, IsIn, IsInt, IsOptional, IsString, Max, Min, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

export const VEDA_STEP_KEYS = ['QUALIFY_LEAD', 'SEND_EMAIL', 'SEND_WHATSAPP', 'VOICE_CALL', 'CHAT_REPLY', 'NURTURE', 'SELF_LEARN'] as const;
export type VedaStepKey = (typeof VEDA_STEP_KEYS)[number];

export interface VedaStepConfig {
  enabled: boolean;
  autoApprove: boolean;
}

export interface VedaConfig {
  globalEnabled: boolean;
  quietHoursStart: string;
  quietHoursEnd: string;
  quietHoursTimezone: string;
  dailyMessageLimit: number;
  steps: Record<VedaStepKey, VedaStepConfig>;
}

// ---- DTOs ----------------------------------------------------------------

export class UpdateStepConfigDto {
  @ApiPropertyOptional() @IsOptional() @IsBoolean() enabled?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() autoApprove?: boolean;
}

export class UpdateVedaConfigDto {
  @ApiPropertyOptional() @IsOptional() @IsBoolean() globalEnabled?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsString() quietHoursStart?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() quietHoursEnd?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() quietHoursTimezone?: string;
  @ApiPropertyOptional() @IsOptional() @IsInt() @Min(1) @Max(1000) dailyMessageLimit?: number;

  @ApiPropertyOptional({ type: UpdateStepConfigDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => UpdateStepConfigDto)
  QUALIFY_LEAD?: UpdateStepConfigDto;

  @ApiPropertyOptional({ type: UpdateStepConfigDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => UpdateStepConfigDto)
  SEND_EMAIL?: UpdateStepConfigDto;

  @ApiPropertyOptional({ type: UpdateStepConfigDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => UpdateStepConfigDto)
  SEND_WHATSAPP?: UpdateStepConfigDto;

  @ApiPropertyOptional({ type: UpdateStepConfigDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => UpdateStepConfigDto)
  VOICE_CALL?: UpdateStepConfigDto;

  @ApiPropertyOptional({ type: UpdateStepConfigDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => UpdateStepConfigDto)
  CHAT_REPLY?: UpdateStepConfigDto;

  @ApiPropertyOptional({ type: UpdateStepConfigDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => UpdateStepConfigDto)
  NURTURE?: UpdateStepConfigDto;

  @ApiPropertyOptional({ type: UpdateStepConfigDto })
  @IsOptional()
  @ValidateNested()
  @Type(() => UpdateStepConfigDto)
  SELF_LEARN?: UpdateStepConfigDto;
}

export class ReviewApprovalDto {
  @ApiPropertyOptional() @IsOptional() @IsString() note?: string;
}

export class ApprovalListQueryDto {
  @ApiPropertyOptional({ enum: ['PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'AUTO_SENT'] })
  @IsOptional()
  @IsIn(['PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'AUTO_SENT'])
  status?: string;

  @ApiPropertyOptional() @IsOptional() limit?: number;
  @ApiPropertyOptional() @IsOptional() offset?: number;
}

export class LogListQueryDto {
  @ApiPropertyOptional() @IsOptional() entityType?: string;
  @ApiPropertyOptional() @IsOptional() entityId?: string;
  @ApiPropertyOptional() @IsOptional() limit?: number;
  @ApiPropertyOptional() @IsOptional() offset?: number;
}

export class CommandDto {
  @ApiProperty({ example: 'Show me the hot leads from Mumbai' })
  @IsString()
  transcript!: string;
}

export class ChatMessageDto {
  @ApiProperty({ description: 'Stable per-visitor session id (generated by the widget)' })
  @IsString()
  sessionId!: string;

  @ApiProperty({ example: 'Do you have a program for stress and clarity?' })
  @IsString()
  message!: string;

  @ApiPropertyOptional() @IsOptional() @IsString() name?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() email?: string;
  @ApiPropertyOptional({ description: 'Visitor WhatsApp / phone number' }) @IsOptional() @IsString() phone?: string;
}
